server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campaign-management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:maxbyte}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:max2max123456!}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.h2.console.enabled=false
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false